//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::blocks::Entity as Blocks;
pub use super::messages::Entity as Messages;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
