//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::chats::Entity as Chats;
pub use super::chat_participants::Entity as ChatParticipants;
pub use super::messages::Entity as Messages;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
